modLoader="javafml"
loaderVersion="[25,)" #mandatory
license="${mod_license}"
[[mods]] #mandatory
modId="minecraftrpg" #mandatory
version="0.1" #mandatory
displayName="Minecraft Rpg" #mandatory

description='''rpg mod for minecraft'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.minecraftrpg]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[25,)" #mandatory
    ordering="NONE"
    side="BOTH"
